version: '3.3'
services:
  metashrew:
    network_mode: 'host'
    image: sandshrewmetaprotocols/metashrew
    build:
      context: ./
      dockerfile: docker/Dockerfile.indexer
    environment:
      - DAEMON_RPC_ADDR=${DAEMON_RPC_ADDR:-127.0.0.1:8332}
      - DAEMON_P2P_ADDR=${DAEMON_P2P_ADDR:-127.0.0.1:8333}
      - NETWORK=${NETWORK:-bitcoin}
      - LOG_FILTERS=${LOG_FILTERS:-INFO}
      - INDEX_BATCH_SIZE=${INDEX_BATCH_SIZE:-2000}
      - MONITORING_ADDR=${MONITORING_ADDR:-127.0.0.1:34442}
      - ELECTRUM_RPC_ADDR=${ELECTRUM_RPC_ADDR:-127.0.0.1:50009}
      - RUST_BACKTRACE=1
    volumes:
      - ${METASHREW_DATA}:/metashrew
      - ${BITCOIN_DATA}:/bitcoin
  metashrew-view:
    network_mode: 'host'
    image: sandshrewmetaprotocols/metashrew-view
    build:
      context: ./
      dockerfile: docker/Dockerfile.view
    environment:
      - PROGRAM_PATH=/metashrew/indexer.wasm
      - DB_LOCATION=/metashrew/rocksdb
      - PORT=${RPC_PORT:-8080}
    volumes:
      - ${METASHREW_DATA}:/metashrew
    restart: unless-stopped
volumes:
  metashrew:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${METASHREW_DATA}
